[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_flags = 
    -D CORE_DEBUG_LEVEL=1
    -D CONFIG_NIMBLE_CPP_LOG_LEVEL=0

lib_deps =
    fastled/FastLED @ ^3.6.0
    h2zero/NimBLE-Arduino @ ^1.4.1
